/*
 * Reise-/Länderempfehlungen — alle Staaten der Welt.
 * Orientiert an gängigen reisemedizinischen Empfehlungen (Auswärtiges Amt, CRM,
 * WHO). KEINE reisemedizinische Beratung — vor Reisen ärztlich beraten lassen.
 *
 * Datenmodell:
 *   REGION_DEFAULTS  Standard-Empfehlungen je Region (Kontinent)
 *   COUNTRIES        alle Länder: { code, name, region, [yf], [required], [recommended], [note] }
 *                    yf:true  → Gelbfieber-Risikoland (wird ergänzt)
 *                    required/recommended/note überschreiben die Regions-Standards
 *   WORLD            Pseudo-Ziel „Weltweiter Impfschutz"
 *
 * Länder ohne eigene Angaben erhalten die Regions-Standardempfehlung.
 */

const REGION_DEFAULTS = {
  Europa: {
    required: [],
    recommended: [],
    note: "Standardimpfungen aktuell halten; in einigen Regionen FSME (Zecken).",
  },
  Asien: {
    required: [],
    recommended: ["hepatitis_a", "typhus", "hepatitis_b", "tollwut", "japanische_enzephalitis"],
    note: "Lebensmittel-/Trinkwasserhygiene beachten; Malaria je nach Region.",
  },
  "Naher Osten": {
    required: [],
    recommended: ["hepatitis_a", "hepatitis_b", "typhus"],
    note: "Standardimpfungen aktuell halten.",
  },
  Afrika: {
    required: [],
    recommended: ["hepatitis_a", "typhus", "hepatitis_b", "tollwut"],
    note: "Malaria-Prophylaxe je nach Region; Gelbfieber in Endemiegebieten.",
  },
  Nordamerika: {
    required: [],
    recommended: ["hepatitis_b"],
    note: "Standardimpfungen inkl. Influenza/COVID-19 aktuell halten.",
  },
  "Mittelamerika & Karibik": {
    required: [],
    recommended: ["hepatitis_a", "typhus", "hepatitis_b", "tollwut"],
    note: "Malaria/Dengue je nach Region.",
  },
  Südamerika: {
    required: [],
    recommended: ["hepatitis_a", "typhus", "hepatitis_b", "tollwut"],
    note: "Gelbfieber in Amazonasregionen; Höhenkrankheit in den Anden.",
  },
  Ozeanien: {
    required: [],
    recommended: ["hepatitis_b"],
    note: "Standardimpfungen aktuell halten.",
  },
};

const COUNTRIES = [
  /* ------------------------------------------------------------ Europa */
  { code: "al", name: "Albanien", region: "Europa" },
  { code: "ad", name: "Andorra", region: "Europa" },
  { code: "at", name: "Österreich", region: "Europa", recommended: ["fsme"], note: "FSME (Zecken) in weiten Teilen Risikogebiet." },
  { code: "ba", name: "Bosnien und Herzegowina", region: "Europa" },
  { code: "be", name: "Belgien", region: "Europa" },
  { code: "bg", name: "Bulgarien", region: "Europa" },
  { code: "by", name: "Belarus", region: "Europa", recommended: ["fsme", "hepatitis_a"] },
  { code: "ch", name: "Schweiz", region: "Europa", recommended: ["fsme"] },
  { code: "cy", name: "Zypern", region: "Europa" },
  { code: "cz", name: "Tschechien", region: "Europa", recommended: ["fsme"], note: "FSME (Zecken) verbreitet." },
  { code: "de", name: "Deutschland", region: "Europa", recommended: ["fsme"], note: "FSME v. a. in Süddeutschland." },
  { code: "dk", name: "Dänemark", region: "Europa" },
  { code: "ee", name: "Estland", region: "Europa", recommended: ["fsme"] },
  { code: "es", name: "Spanien", region: "Europa" },
  { code: "fi", name: "Finnland", region: "Europa", recommended: ["fsme"] },
  { code: "fr", name: "Frankreich", region: "Europa" },
  { code: "gb", name: "Vereinigtes Königreich", region: "Europa" },
  { code: "gr", name: "Griechenland", region: "Europa" },
  { code: "hr", name: "Kroatien", region: "Europa", recommended: ["fsme"] },
  { code: "hu", name: "Ungarn", region: "Europa", recommended: ["fsme"] },
  { code: "ie", name: "Irland", region: "Europa" },
  { code: "is", name: "Island", region: "Europa" },
  { code: "it", name: "Italien", region: "Europa" },
  { code: "li", name: "Liechtenstein", region: "Europa", recommended: ["fsme"] },
  { code: "lt", name: "Litauen", region: "Europa", recommended: ["fsme"] },
  { code: "lu", name: "Luxemburg", region: "Europa" },
  { code: "lv", name: "Lettland", region: "Europa", recommended: ["fsme"] },
  { code: "mc", name: "Monaco", region: "Europa" },
  { code: "md", name: "Moldau", region: "Europa", recommended: ["fsme", "hepatitis_a"] },
  { code: "me", name: "Montenegro", region: "Europa" },
  { code: "mk", name: "Nordmazedonien", region: "Europa" },
  { code: "mt", name: "Malta", region: "Europa" },
  { code: "nl", name: "Niederlande", region: "Europa" },
  { code: "no", name: "Norwegen", region: "Europa" },
  { code: "pl", name: "Polen", region: "Europa", recommended: ["fsme"] },
  { code: "pt", name: "Portugal", region: "Europa" },
  { code: "ro", name: "Rumänien", region: "Europa" },
  { code: "rs", name: "Serbien", region: "Europa" },
  { code: "ru", name: "Russland", region: "Europa", recommended: ["hepatitis_a", "hepatitis_b", "typhus", "fsme", "tollwut"], note: "FSME weit verbreitet; Tollwut bei Landaufenthalt." },
  { code: "se", name: "Schweden", region: "Europa", recommended: ["fsme"] },
  { code: "si", name: "Slowenien", region: "Europa", recommended: ["fsme"] },
  { code: "sk", name: "Slowakei", region: "Europa", recommended: ["fsme"] },
  { code: "sm", name: "San Marino", region: "Europa" },
  { code: "ua", name: "Ukraine", region: "Europa", recommended: ["hepatitis_a", "hepatitis_b", "fsme", "tollwut"] },
  { code: "va", name: "Vatikanstadt", region: "Europa" },
  { code: "xk", name: "Kosovo", region: "Europa" },

  /* ------------------------------------------------------------- Asien */
  { code: "af", name: "Afghanistan", region: "Asien" },
  { code: "am", name: "Armenien", region: "Asien" },
  { code: "az", name: "Aserbaidschan", region: "Asien" },
  { code: "bd", name: "Bangladesch", region: "Asien" },
  { code: "bn", name: "Brunei", region: "Asien" },
  { code: "bt", name: "Bhutan", region: "Asien" },
  { code: "cn", name: "China", region: "Asien", recommended: ["hepatitis_a", "typhus", "hepatitis_b", "japanische_enzephalitis", "tollwut"], note: "Japanische Enzephalitis v. a. in ländlichen Gebieten Ost-/Südchinas." },
  { code: "ge", name: "Georgien", region: "Asien", recommended: ["hepatitis_a", "hepatitis_b", "tollwut"] },
  { code: "id", name: "Indonesien (inkl. Bali)", region: "Asien", recommended: ["hepatitis_a", "typhus", "hepatitis_b", "tollwut", "japanische_enzephalitis"], note: "Tollwut auf Bali relevant. Malaria je nach Region." },
  { code: "in", name: "Indien", region: "Asien", recommended: ["hepatitis_a", "typhus", "hepatitis_b", "tollwut", "japanische_enzephalitis", "cholera"], note: "Poliomyelitis-Schutz sicherstellen. Gelbfieber-Nachweis nur bei Einreise aus Endemiegebiet." },
  { code: "jp", name: "Japan", region: "Asien", recommended: ["hepatitis_a", "japanische_enzephalitis"], note: "Insgesamt geringes Risiko; JE nur bei Langzeit/Landaufenthalt." },
  { code: "kg", name: "Kirgisistan", region: "Asien" },
  { code: "kh", name: "Kambodscha", region: "Asien" },
  { code: "kp", name: "Nordkorea", region: "Asien" },
  { code: "kr", name: "Südkorea", region: "Asien", recommended: ["hepatitis_a", "hepatitis_b", "japanische_enzephalitis"] },
  { code: "kz", name: "Kasachstan", region: "Asien" },
  { code: "la", name: "Laos", region: "Asien" },
  { code: "lk", name: "Sri Lanka", region: "Asien" },
  { code: "mm", name: "Myanmar", region: "Asien" },
  { code: "mn", name: "Mongolei", region: "Asien", recommended: ["hepatitis_a", "hepatitis_b", "tollwut"] },
  { code: "mv", name: "Malediven", region: "Asien", recommended: ["hepatitis_a", "typhus", "hepatitis_b"] },
  { code: "my", name: "Malaysia", region: "Asien" },
  { code: "np", name: "Nepal", region: "Asien", recommended: ["hepatitis_a", "typhus", "hepatitis_b", "tollwut", "japanische_enzephalitis"], note: "Höhenkrankheit beachten (keine Impfung)." },
  { code: "ph", name: "Philippinen", region: "Asien" },
  { code: "pk", name: "Pakistan", region: "Asien", recommended: ["hepatitis_a", "typhus", "hepatitis_b", "tollwut", "poliomyelitis"] },
  { code: "sg", name: "Singapur", region: "Asien", recommended: ["hepatitis_a", "hepatitis_b"] },
  { code: "th", name: "Thailand", region: "Asien", recommended: ["hepatitis_a", "typhus", "hepatitis_b", "tollwut", "japanische_enzephalitis"], note: "Japanische Enzephalitis v. a. bei Reisen aufs Land/Langzeit. Malaria in Grenzregionen." },
  { code: "tj", name: "Tadschikistan", region: "Asien" },
  { code: "tl", name: "Timor-Leste", region: "Asien" },
  { code: "tm", name: "Turkmenistan", region: "Asien" },
  { code: "tw", name: "Taiwan", region: "Asien", recommended: ["hepatitis_a", "hepatitis_b", "japanische_enzephalitis"] },
  { code: "uz", name: "Usbekistan", region: "Asien" },
  { code: "vn", name: "Vietnam", region: "Asien", recommended: ["hepatitis_a", "typhus", "hepatitis_b", "tollwut", "japanische_enzephalitis"], note: "Japanische Enzephalitis bei Landaufenthalt/Regenzeit." },

  /* -------------------------------------------------------- Naher Osten */
  { code: "ae", name: "Vereinigte Arabische Emirate", region: "Naher Osten", note: "Moderne Infrastruktur; Standardimpfungen aktualisieren." },
  { code: "bh", name: "Bahrain", region: "Naher Osten" },
  { code: "il", name: "Israel", region: "Naher Osten" },
  { code: "iq", name: "Irak", region: "Naher Osten" },
  { code: "ir", name: "Iran", region: "Naher Osten" },
  { code: "jo", name: "Jordanien", region: "Naher Osten" },
  { code: "kw", name: "Kuwait", region: "Naher Osten" },
  { code: "lb", name: "Libanon", region: "Naher Osten" },
  { code: "om", name: "Oman", region: "Naher Osten" },
  { code: "ps", name: "Palästina", region: "Naher Osten" },
  { code: "qa", name: "Katar", region: "Naher Osten" },
  { code: "sa", name: "Saudi-Arabien", region: "Naher Osten", required: ["meningokokken_acwy"], recommended: ["hepatitis_a", "hepatitis_b", "typhus"], note: "Meningokokken ACWY ist für Hadsch/Umra Pflicht. Gelbfieber bei Einreise aus Endemiegebiet." },
  { code: "sy", name: "Syrien", region: "Naher Osten" },
  { code: "tr", name: "Türkei", region: "Naher Osten", note: "Bei Reisen abseits der Touristenzentren erhöhtes Risiko." },
  { code: "ye", name: "Jemen", region: "Naher Osten" },

  /* ------------------------------------------------------------ Afrika */
  { code: "ao", name: "Angola", region: "Afrika", yf: true },
  { code: "bf", name: "Burkina Faso", region: "Afrika", yf: true },
  { code: "bi", name: "Burundi", region: "Afrika", yf: true },
  { code: "bj", name: "Benin", region: "Afrika", yf: true },
  { code: "bw", name: "Botswana", region: "Afrika" },
  { code: "cd", name: "Kongo (Dem. Rep.)", region: "Afrika", yf: true },
  { code: "cf", name: "Zentralafrikanische Republik", region: "Afrika", yf: true },
  { code: "cg", name: "Kongo (Rep.)", region: "Afrika", yf: true },
  { code: "ci", name: "Elfenbeinküste", region: "Afrika", yf: true },
  { code: "cm", name: "Kamerun", region: "Afrika", yf: true },
  { code: "cv", name: "Kap Verde", region: "Afrika" },
  { code: "dj", name: "Dschibuti", region: "Afrika" },
  { code: "dz", name: "Algerien", region: "Afrika" },
  { code: "eg", name: "Ägypten", region: "Afrika", recommended: ["hepatitis_a", "typhus", "hepatitis_b", "tollwut"], note: "Durchfallerkrankungen und Hepatitis A häufig." },
  { code: "er", name: "Eritrea", region: "Afrika" },
  { code: "et", name: "Äthiopien", region: "Afrika", yf: true },
  { code: "ga", name: "Gabun", region: "Afrika", yf: true },
  { code: "gh", name: "Ghana", region: "Afrika", yf: true, required: ["gelbfieber"], recommended: ["hepatitis_a", "typhus", "hepatitis_b", "tollwut", "meningokokken_acwy"], note: "Gelbfieber ist Pflichtimpfung bei Einreise. Malaria-Prophylaxe empfohlen." },
  { code: "gm", name: "Gambia", region: "Afrika", yf: true },
  { code: "gn", name: "Guinea", region: "Afrika", yf: true },
  { code: "gq", name: "Äquatorialguinea", region: "Afrika", yf: true },
  { code: "gw", name: "Guinea-Bissau", region: "Afrika", yf: true },
  { code: "ke", name: "Kenia", region: "Afrika", yf: true, required: ["gelbfieber"], recommended: ["hepatitis_a", "typhus", "hepatitis_b", "tollwut", "meningokokken_acwy"], note: "Gelbfieber bei Einreise oft Pflicht. Malaria-Prophylaxe empfohlen." },
  { code: "km", name: "Komoren", region: "Afrika" },
  { code: "lr", name: "Liberia", region: "Afrika", yf: true },
  { code: "ls", name: "Lesotho", region: "Afrika" },
  { code: "ly", name: "Libyen", region: "Afrika" },
  { code: "ma", name: "Marokko", region: "Afrika", recommended: ["hepatitis_a", "typhus", "hepatitis_b", "tollwut"], note: "Hygiene bei Straßenessen beachten." },
  { code: "mg", name: "Madagaskar", region: "Afrika" },
  { code: "ml", name: "Mali", region: "Afrika", yf: true },
  { code: "mr", name: "Mauretanien", region: "Afrika", yf: true },
  { code: "mu", name: "Mauritius", region: "Afrika" },
  { code: "mw", name: "Malawi", region: "Afrika" },
  { code: "mz", name: "Mosambik", region: "Afrika" },
  { code: "na", name: "Namibia", region: "Afrika" },
  { code: "ne", name: "Niger", region: "Afrika", yf: true },
  { code: "ng", name: "Nigeria", region: "Afrika", yf: true },
  { code: "rw", name: "Ruanda", region: "Afrika" },
  { code: "sc", name: "Seychellen", region: "Afrika" },
  { code: "sd", name: "Sudan", region: "Afrika", yf: true },
  { code: "sl", name: "Sierra Leone", region: "Afrika", yf: true },
  { code: "sn", name: "Senegal", region: "Afrika", yf: true },
  { code: "so", name: "Somalia", region: "Afrika" },
  { code: "ss", name: "Südsudan", region: "Afrika", yf: true },
  { code: "st", name: "São Tomé und Príncipe", region: "Afrika" },
  { code: "sz", name: "Eswatini", region: "Afrika" },
  { code: "td", name: "Tschad", region: "Afrika", yf: true },
  { code: "tg", name: "Togo", region: "Afrika", yf: true },
  { code: "tn", name: "Tunesien", region: "Afrika" },
  { code: "tz", name: "Tansania (inkl. Sansibar)", region: "Afrika", yf: true, required: ["gelbfieber"], recommended: ["hepatitis_a", "typhus", "hepatitis_b", "tollwut"], note: "Gelbfieber-Pflicht v. a. bei Einreise aus Endemiegebiet. Malaria-Risiko." },
  { code: "ug", name: "Uganda", region: "Afrika", yf: true },
  { code: "za", name: "Südafrika", region: "Afrika", recommended: ["hepatitis_a", "typhus", "hepatitis_b", "tollwut"], note: "Malaria im Nordosten (Krüger-Nationalpark)." },
  { code: "zm", name: "Sambia", region: "Afrika" },
  { code: "zw", name: "Simbabwe", region: "Afrika" },

  /* -------------------------------------------------------- Nordamerika */
  { code: "ca", name: "Kanada", region: "Nordamerika" },
  { code: "mx", name: "Mexiko", region: "Nordamerika", recommended: ["hepatitis_a", "typhus", "hepatitis_b", "tollwut"], note: "Magen-Darm-Infekte und Hepatitis A verbreitet." },
  { code: "us", name: "USA", region: "Nordamerika", recommended: ["hepatitis_b"], note: "Standardimpfungen inkl. Influenza/COVID-19 aktuell halten." },

  /* --------------------------------------------- Mittelamerika & Karibik */
  { code: "bb", name: "Barbados", region: "Mittelamerika & Karibik" },
  { code: "bs", name: "Bahamas", region: "Mittelamerika & Karibik" },
  { code: "bz", name: "Belize", region: "Mittelamerika & Karibik" },
  { code: "cr", name: "Costa Rica", region: "Mittelamerika & Karibik" },
  { code: "cu", name: "Kuba", region: "Mittelamerika & Karibik" },
  { code: "dm", name: "Dominica", region: "Mittelamerika & Karibik" },
  { code: "do", name: "Dominikanische Republik", region: "Mittelamerika & Karibik" },
  { code: "gd", name: "Grenada", region: "Mittelamerika & Karibik" },
  { code: "gt", name: "Guatemala", region: "Mittelamerika & Karibik" },
  { code: "hn", name: "Honduras", region: "Mittelamerika & Karibik" },
  { code: "ht", name: "Haiti", region: "Mittelamerika & Karibik" },
  { code: "jm", name: "Jamaika", region: "Mittelamerika & Karibik" },
  { code: "kn", name: "St. Kitts und Nevis", region: "Mittelamerika & Karibik" },
  { code: "lc", name: "St. Lucia", region: "Mittelamerika & Karibik" },
  { code: "ni", name: "Nicaragua", region: "Mittelamerika & Karibik" },
  { code: "pa", name: "Panama", region: "Mittelamerika & Karibik", yf: true },
  { code: "sv", name: "El Salvador", region: "Mittelamerika & Karibik" },
  { code: "tt", name: "Trinidad und Tobago", region: "Mittelamerika & Karibik", yf: true },
  { code: "vc", name: "St. Vincent und die Grenadinen", region: "Mittelamerika & Karibik" },

  /* --------------------------------------------------------- Südamerika */
  { code: "ar", name: "Argentinien", region: "Südamerika", yf: true, recommended: ["hepatitis_a", "hepatitis_b"], note: "Gelbfieber nur für bestimmte nördliche Regionen empfohlen." },
  { code: "bo", name: "Bolivien", region: "Südamerika", yf: true },
  { code: "br", name: "Brasilien", region: "Südamerika", yf: true, recommended: ["hepatitis_a", "typhus", "hepatitis_b", "tollwut"], note: "Gelbfieber für viele Regionen (Amazonas u. a.) dringend empfohlen." },
  { code: "cl", name: "Chile", region: "Südamerika", recommended: ["hepatitis_a", "hepatitis_b"] },
  { code: "co", name: "Kolumbien", region: "Südamerika", yf: true },
  { code: "ec", name: "Ecuador", region: "Südamerika", yf: true },
  { code: "gy", name: "Guyana", region: "Südamerika", yf: true },
  { code: "pe", name: "Peru", region: "Südamerika", yf: true, recommended: ["hepatitis_a", "typhus", "hepatitis_b", "tollwut"], note: "Gelbfieber bei Reisen in Amazonasgebiete empfohlen." },
  { code: "py", name: "Paraguay", region: "Südamerika", yf: true },
  { code: "sr", name: "Suriname", region: "Südamerika", yf: true },
  { code: "uy", name: "Uruguay", region: "Südamerika", recommended: ["hepatitis_a", "hepatitis_b"] },
  { code: "ve", name: "Venezuela", region: "Südamerika", yf: true },

  /* ----------------------------------------------------------- Ozeanien */
  { code: "au", name: "Australien", region: "Ozeanien", note: "Guter medizinischer Standard; Standardimpfungen prüfen." },
  { code: "fj", name: "Fidschi", region: "Ozeanien", recommended: ["hepatitis_a", "hepatitis_b", "typhus"] },
  { code: "fm", name: "Mikronesien", region: "Ozeanien" },
  { code: "ki", name: "Kiribati", region: "Ozeanien" },
  { code: "mh", name: "Marshallinseln", region: "Ozeanien" },
  { code: "nr", name: "Nauru", region: "Ozeanien" },
  { code: "nz", name: "Neuseeland", region: "Ozeanien" },
  { code: "pg", name: "Papua-Neuguinea", region: "Ozeanien", recommended: ["hepatitis_a", "typhus", "hepatitis_b", "tollwut", "japanische_enzephalitis"] },
  { code: "pw", name: "Palau", region: "Ozeanien" },
  { code: "sb", name: "Salomonen", region: "Ozeanien" },
  { code: "to", name: "Tonga", region: "Ozeanien" },
  { code: "tv", name: "Tuvalu", region: "Ozeanien" },
  { code: "vu", name: "Vanuatu", region: "Ozeanien" },
  { code: "ws", name: "Samoa", region: "Ozeanien" },
];

// Pseudo-Ziel für allgemeinen weltweiten Impfschutz.
const WORLD = {
  code: "world",
  name: "Weltweiter Impfschutz",
  region: "Weltweit",
  required: [],
  recommended: [], // wird in app.js als Vereinigung aller Länder berechnet
  note: "Umfasst sämtliche Reiseimpfungen, die weltweit für irgendein Reiseziel empfohlen oder gefordert werden. Standardimpfungen (Tetanus, Diphtherie, Keuchhusten, Poliomyelitis, MMR) zusätzlich aktuell halten.",
};

// Kurze Infos zu ausgewählten Ländern.
const COUNTRY_INFO = {
  world: "Allgemein empfohlener Impfschutz für Reisen rund um den Globus — unabhängig vom konkreten Ziel.",
  th: "Beliebtes Reiseziel Südostasiens; gute Versorgung in Städten, einfachere Bedingungen auf dem Land.",
  in: "Große hygienische Unterschiede; Durchfallerkrankungen häufig – Trinkwasser- und Lebensmittelhygiene besonders wichtig.",
  id: "Inselstaat mit tropischem Klima; Tollwut u. a. auf Bali, Versorgung außerhalb der Ballungsräume begrenzt.",
  vn: "Tropisches Klima; Japanische Enzephalitis in Reisanbaugebieten, Lebensmittelhygiene wichtig.",
  np: "Trekking-Ziel; Höhenkrankheit und Magen-Darm-Infekte sind die Hauptrisiken.",
  cn: "Sehr unterschiedliche Regionen; in Metropolen gute Versorgung, ländliche Gebiete einfacher.",
  jp: "Hoher Hygienestandard, geringes Infektionsrisiko; JE nur bei Langzeit-/Landaufenthalt.",
  ke: "Safari- und Küstenreisen; Malaria und Gelbfieber sind die zentralen Themen.",
  tz: "Inkl. Sansibar; Malaria landesweit, Gelbfiebernachweis je nach Einreiseweg.",
  za: "Gute Versorgung in Städten; Malaria v. a. im Nordosten (Krüger-Nationalpark).",
  gh: "Westafrika; Gelbfieber ist Pflicht, Malaria ganzjährig.",
  eg: "Nil- und Badereisen; Durchfallerkrankungen und Hepatitis A häufig.",
  ma: "Nordafrika; überwiegend gute Bedingungen, Hygiene bei Straßenessen beachten.",
  br: "Von Metropolen bis Amazonas; Gelbfieber je nach Region wichtig.",
  pe: "Anden und Amazonas; Höhenkrankheit in Cusco, Gelbfieber im Tiefland.",
  us: "Hoher medizinischer Standard, aber teuer – Auslandskrankenversicherung wichtig.",
  ar: "Von den Subtropen bis Patagonien; Gelbfieber nur im Nordosten relevant.",
  sa: "Für Hadsch/Umra gelten besondere Impfvorschriften (Meningokokken ACWY Pflicht).",
  ae: "Moderne Infrastruktur und Versorgung; Standardimpfungen aktualisieren.",
  tr: "Beliebtes Reiseland; abseits der Touristenzentren erhöhtes Infektionsrisiko.",
  at: "Nachbarland; FSME durch Zecken ist das Hauptthema.",
  ru: "Sehr großes Land; FSME weit verbreitet, Tollwut bei Landaufenthalt.",
  au: "Guter medizinischer Standard; lange Anreise, Standardimpfungen prüfen.",
};

window.TRAVEL = { COUNTRIES, REGION_DEFAULTS, WORLD, COUNTRY_INFO };
